scheduler.jdbc.thread-pool-size: 10
spring:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: api-webflux
  datasource:
    url: jdbc:mysql://localhost:3306/webflux?useSSL=false
    username: webflux
    password: webflux
  jackson.property-naming-strategy: SNAKE_CASE
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB